FROM docker.cloudsmith.io/ultimaker/docker-public/deb-stretch_xcomp_gnueabihf:latest

LABEL Maintainer="software-embedded-platform@ultimaker.com" \
      Comment="Ultimaker kernel build environment"

COPY buildenv_check.sh buildenv_check.sh
