# SPDX-License-Identifier: AGPL-3.0+
#
# Copyright (C) 2018 Ultimaker B.V.
# Copyright (C) 2018 Olliver Schinagl <oliver@schinagl.nl>
#
# GitLab CI package build is split up into two parts.
# * Build environment: creates the docker image that is needed for package generation
# * Package generation: creates the final artifact

stages:
- lint
- prepare
- verify
- push
- build
- cleanup

# Common requisites
# ==========
.parameters_template: &parameters_common
  tags:
  - embedded
  - docker

lint build environment test:
  <<: *parameters_common
  image: registry.hub.docker.com/koalaman/shellcheck-alpine:stable
  stage: lint
  script:
  - shellcheck -C -f tty -s sh tests/buildenv.sh

# Build environment
# =================
.build environment template: &buildenv_common
  <<: *parameters_common
  image: registry.hub.docker.com/library/docker:stable
  only:
    variables:
    - $CI_COMMIT_MESSAGE =~ /dockerfile/i

prepare build environment:
  <<: *buildenv_common
  stage: prepare
  script:
  - docker build --rm -t "$CI_COMMIT_SHA:$CI_PIPELINE_ID" .

verify build environment:
  stage: verify
  <<: *buildenv_common
  script:
    - docker run --rm "$CI_COMMIT_SHA:$CI_PIPELINE_ID" /tests/buildenv.sh

push build environment:
  <<: *buildenv_common
  except:
  - /^(?!master$)/
  stage: push
  script:
  - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
  - docker tag  "$CI_COMMIT_SHA:$CI_PIPELINE_ID" "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  - docker tag  "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE:latest"
  - docker push "$CI_REGISTRY_IMAGE:latest"

cleanup build environment:
  <<: *buildenv_common
  stage: cleanup
  when: always
  script:
  - |
    if docker inspect --type image "$CI_COMMIT_SHA:$CI_PIPELINE_ID" 1> /dev/null; then
      docker rmi "$CI_COMMIT_SHA:$CI_PIPELINE_ID"
    fi

# Package generation
# ==================
.build pkg template: &pkg_common
  <<: *parameters_common
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  image: "$CI_REGISTRY_IMAGE:latest"

build package:
  <<: *pkg_common
  stage: build
  script:
  - ./build.sh
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA"
    paths:
    - ./*.deb
    expire_in: 3 days
