# yamllint disable rule:line-length
# SPDX-License-Identifier: AGPL-3.0+
#
# Copyright (C) 2019 Ultimaker B.V.

include:
  - project: ultimaker/embedded/platform/alt_prime_jedi
    ref: CHANGE_use_extend_instead_of_anchors
    file: /gitlab_ci_templates/jedi-gitlab-ci-template.yml

# Build stage
# ===========
build:
  script:
    - ci/add_private_key.sh
    - ./build.sh
