# yamllint disable rule:line-length
#
# Copyright (C) 2019 Ultimaker B.V.

include:
  - project: ultimaker/embedded/prime-jedi
    ref: master
    file: /gitlab_ci_templates/jedi-gitlab-ci-template.yml
