# yamllint disable rule:line-length
# SPDX-License-Identifier: AGPL-3.0+
#
# Copyright (C) 2019 Ultimaker B.V.

include:
  - project: ultimaker/embedded/prime-jedi
    ref: master
    file: /gitlab_ci_templates/jedi-gitlab-ci-template.yml

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Build stage
# ===========
build:
  timeout: 2h
  extends:
    - .retrieve_source
  script:
    - ci/add_private_key.sh
    - ./build.sh
    - cp -v ./_build*/*.deb "./"
