#!/usr/bin/env bash
# Auto-generated by ultimaker-agentic-bootstrap from detected repo tooling.
# Runs the repository's own linters/formatters on files changed since HEAD.
set -uo pipefail

# Antigravity invokes hooks with cwd set to the hooks.json directory —
# always operate from the repository root.
cd "$(git rev-parse --show-toplevel)" || exit 0

FAIL=0

# Lint what this edit actually wrote, not everything the branch has touched.
# A PostToolUse payload names the edited file on stdin; when it does, that one
# path is the deliverable. Linting `git diff --name-only HEAD` on EVERY edit
# re-reported the same findings about untouched files over and over — which is
# how hook output stops being read — and its cost grew with the length of the
# branch rather than the size of the edit.
#
# Explicit arguments win over the payload, and the whole working diff remains
# the fallback, so nothing is skipped when no path can be determined.
CHANGED=""
if [ "$#" -gt 0 ]; then
    CHANGED=$(printf '%s\n' "$@")
elif [ ! -t 0 ]; then
    CHANGED=$(python3 -c '
import json, sys

PATH_KEYS = ("file_path", "filePath", "path", "target_file", "TargetFile", "absolute_path", "notebook_path", "filename")

def find_paths(obj):
    found = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            if k in PATH_KEYS and isinstance(v, str) and v.strip():
                found.append(v.strip())
            else:
                found.extend(find_paths(v))
    elif isinstance(obj, list):
        for item in obj:
            found.extend(find_paths(item))
    return found

try:
    payload = json.load(sys.stdin)
    inp = payload.get("tool_input") or payload
    paths = find_paths(inp)
    print("\n".join(dict.fromkeys(paths)))
except Exception:
    sys.exit(0)
' 2>/dev/null || true)
fi

if [ -z "$CHANGED" ]; then
    CHANGED=$(git diff --name-only HEAD 2>/dev/null | head -100)
fi

# Paths arrive absolute from the payload; every tool below expects them
# relative to the repository root.
if [ -n "$CHANGED" ]; then
    CHANGED=$(printf '%s\n' "$CHANGED" | sed "s|^$(pwd)/||" | grep -v '^$' || true)
fi

if [ -z "$CHANGED" ]; then
    exit 0
fi

# This repository's OWN lint entry points, found by the bootstrap investigation.
# Firmware repositories keep these in ci/ or tools/ rather than at the root, so
# a hook that only knew about root-level configs ran nothing at all here.
if [ -x "run_shellcheck.sh" ] || [ -f "run_shellcheck.sh" ]; then
    ./run_shellcheck.sh || FAIL=1
fi
if [ -f .agents/hooks/check_file_size_budget.py ]; then
    python3 .agents/hooks/check_file_size_budget.py --changed || FAIL=1
fi

if [ -f .agents/hooks/check_complexity.py ]; then
    # Scoped to the files this edit wrote (see CHANGED above): the gate reports
    # on the deliverable, not on every file the branch has ever touched.
    # shellcheck disable=SC2086
    python3 .agents/hooks/check_complexity.py --changed $CHANGED || true
fi

# Skill suggestions are deliberately NOT invoked here. Injecting "you should
# have loaded skill X" after the edit has already landed is advice that arrives
# too late to act on. suggest-skills.py is wired as a PRE-edit hook instead,
# and only for the harnesses that need it — Claude resolves skills from the
# `paths:` front matter in its own rules.

exit $FAIL
