#!/bin/bash
# Make sure /boot is mounted before unpacking.

# The bootstraping tool does not run the debian "preinst" scripts before unpacking
# so it is safe to place commands to be run just in a running printer.

# Check if /boot is already monted
if ! mountpoint -q /boot; then

    # Get the root partition
    root_part=$(findmnt -o source -n /)

    # Set the device for the boot partition
    boot_part=${root_part/%p2/p1}

    mount "${boot_part}" /boot
fi
