#!/bin/sh
# special version for MSC SMARC imx6 in new ultimaker main board

export_output() {
        echo $1 > /sys/class/gpio/export
        echo "out" > /sys/class/gpio/gpio$1/direction
        ln -s /sys/class/gpio/gpio$1/value /dev/gpio/$2
        chmod 666 /sys/class/gpio/gpio$1/value
}
export_input() {
        echo $1 > /sys/class/gpio/export
        echo "in" > /sys/class/gpio/gpio$1/direction
        ln -s /sys/class/gpio/gpio$1/value /dev/gpio/$2
}

mkdir /dev/gpio 2> /dev/null

## export_output 44 avr_reset   # for MSC carrier board SMARC GPIO10 = linux gpio44 (gpio2.12)
export_output 41 avr_reset  # for new ulti main board SMARC GPIO5 = linux gpio41 (gpio2.9)
export_output 117 avr_sck
export_output 118 avr_mosi
export_input 119 avr_miso
export_output 120 avr_ss0  # essential for new ulti main board - was commented out for MSC carrier board.
echo 0 > /dev/gpio/avr_ss0
#export_output 121 avr_ss1

# 