#!/usr/bin/env bash
# @generated by the agentic bootstrap. Regenerated on every run; the absence
# of this header is how the writer recognises a hand-written file and refuses
# to overwrite it. Edit the bootstrap, not this file.
# create_boyscout_branch_and_pr.sh
#
# Extract an opportunistic fix ("boy scouting") off the current feature branch
# onto its own branch and draft PR, so the primary PR keeps a single intent.
#
# Rule 08 and two generated hooks tell agents to run this script. The generator
# used to emit those references without ever emitting the script, so the advice
# dead-ended at "No such file or directory" — the bootstrap must emit whatever
# it tells an agent to run.
#
# Usage:
#   bash scripts/create_boyscout_branch_and_pr.sh <JIRA-KEY> <topic> <path>...
# Example:
#   bash scripts/create_boyscout_branch_and_pr.sh EMB-370 stale-readme README.md

set -euo pipefail

if [ "$#" -lt 3 ]; then
    echo "Usage: $0 <JIRA-KEY> <topic> <path>..." >&2
    echo "Example: $0 EMB-370 stale-readme README.md" >&2
    exit 2
fi

TICKET="$1"; shift
TOPIC="$1"; shift
PATHS=("$@")

if ! printf '%s' "$TICKET" | grep -Eq '^[A-Z][A-Z0-9]{1,9}-[0-9]+$'; then
    echo "ERROR: '$TICKET' is not a Jira ticket key (e.g. EMB-370)." >&2
    exit 2
fi

BASE_BRANCH=$(python3 -c \
    'import json;print(json.load(open(".agents/bootstrap-profile.json")).get("base_branch","master/imx8"))' \
    2>/dev/null || echo "master/imx8")
ORIGINAL_BRANCH=$(git rev-parse --abbrev-ref HEAD)
# Hyphens, not underscores: branch names read as `TICKET-topic`.
BRANCH="${TICKET}-${TOPIC}"

for path in "${PATHS[@]}"; do
    if [ ! -e "$path" ]; then
        echo "ERROR: '$path' does not exist." >&2
        exit 2
    fi
done

REPO_ROOT=$(git rev-parse --show-toplevel)
SAVE_DIR=$(mktemp -d)

# Deliberately not `git stash`. `refs/stash` is a single ref shared by every
# worktree of a clone, and `git stash pop` always pops stash@{0} — which may
# belong to another worktree. A concurrent pop replays, and destroys, work
# from a tree this script never looked at.
echo "==> Saving the boy-scout paths off ${ORIGINAL_BRANCH}"
tar -cf "${SAVE_DIR}/boyscout.tar" -C "${REPO_ROOT}" -- "${PATHS[@]}"

restore() {
    tar -xf "${SAVE_DIR}/boyscout.tar" -C "${REPO_ROOT}"
}

cleanup() {
    echo "==> Restoring the boy-scout paths after failure" >&2
    git checkout -q "${ORIGINAL_BRANCH}" 2>/dev/null || true
    restore
    rm -rf "${SAVE_DIR}"
}
trap cleanup ERR

# Clear the paths so the branch switch is clean, without touching any other
# file: tracked paths go back to HEAD, paths git never knew about are removed.
for path in "${PATHS[@]}"; do
    if git ls-files --error-unmatch -- "$path" >/dev/null 2>&1; then
        git checkout -- "$path"
    else
        rm -rf -- "$path"
    fi
done

echo "==> Branching ${BRANCH} from origin/${BASE_BRANCH}"
git fetch origin "${BASE_BRANCH}" --quiet
git checkout -q -b "${BRANCH}" "origin/${BASE_BRANCH}"

restore
rm -rf "${SAVE_DIR}"
trap - ERR
git add -- "${PATHS[@]}"
git commit -q -m "[${TICKET}] ${TOPIC//-/ }"

echo "==> Pushing ${BRANCH}"
git push -u origin "${BRANCH}" --quiet

# Draft only: merging is a human decision (rule 06).
gh pr create --draft --base "${BASE_BRANCH}" --head "${BRANCH}" \
    --title "[${TICKET}] ${TOPIC//-/ }" \
    --body "Boy-scouting extraction from \`${ORIGINAL_BRANCH}\`, kept separate so
that branch stays single-intent (see \`.agents/rules/08-scoped-changes-and-minimal-diffs.md\`).

## Why
Opportunistic fix noticed while working on \`${ORIGINAL_BRANCH}\`.

## What
Changes limited to: ${PATHS[*]}

## How
Extracted verbatim; no other files touched.

## Verification & Validation (V&V)
- [ ] \`bash scripts/verify_and_create_pr.sh\` passes on this branch

## PR Checklist
- [ ] Initiating developer reviewed AI-generated code"

echo "==> Returning to ${ORIGINAL_BRANCH}"
git checkout -q "${ORIGINAL_BRANCH}"
