#!/bin/sh
# @generated by the agentic bootstrap. Regenerated on every run; the absence
# of this header is how the writer recognises a hand-written file and refuses
# to overwrite it. Edit the bootstrap, not this file.
# get_github_token.sh — keyring-first GITHUB_TOKEN retrieval (POSIX sh).
#
# Source this from any script that needs a GitHub token with read:packages:
#     . scripts/get_github_token.sh
#
# Retrieval chain (first hit wins):
#   1. an already-exported GITHUB_TOKEN
#   2. the system keyring — Linux: secret-tool (libsecret),
#      macOS: security (Keychain)
#   3. a gitignored .env / .env.local fallback, with a warning
#
# Storing the token (run ONCE, by a human — never scripted, never echoed
# into history with the token on the command line where avoidable):
#   Linux:  echo -n "<PAT>" | secret-tool store --label="$USER-github-token" \
#               service github user "$USER"
#   macOS:  security add-generic-password -s github -a "$USER" -w
#           (prompts for the secret interactively)
#
# The token is never written to disk or logs by this script.

if [ -z "${GITHUB_TOKEN:-}" ]; then
    if command -v secret-tool >/dev/null 2>&1; then
        GITHUB_TOKEN="$(secret-tool lookup service github user "$USER" 2>/dev/null || true)"
    elif command -v security >/dev/null 2>&1; then
        GITHUB_TOKEN="$(security find-generic-password -s github -a "$USER" -w 2>/dev/null || true)"
    fi
fi

if [ -z "${GITHUB_TOKEN:-}" ]; then
    for env_file in .env.local .env; do
        if [ -f "$env_file" ]; then
            GITHUB_TOKEN="$(sed -n 's/^GITHUB_TOKEN=//p' "$env_file" | head -1 | tr -d '"')"
            if [ -n "$GITHUB_TOKEN" ]; then
                echo "WARNING: GITHUB_TOKEN read from gitignored $env_file." >&2
                echo "         Prefer the system keyring (see scripts/get_github_token.sh)." >&2
                break
            fi
        fi
    done
fi

if [ -n "${GITHUB_TOKEN:-}" ]; then
    export GITHUB_TOKEN
else
    echo "WARNING: no GITHUB_TOKEN found (env, keyring, or .env fallback)." >&2
fi
