name: Build package on Push

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'docker_img-v*'
  
jobs:
  Prepare:
    name: 'Prepare'
    uses: Ultimaker/embedded-workflows/.github/workflows/prepare_env.yml@main
    secrets: inherit

  Shellcheck:
    name: 'Test'
    needs: Prepare
    uses: Ultimaker/embedded-workflows/.github/workflows/shellcheck.yml@main
    secrets: inherit
         
  Build:
    name: 'Build'
    needs: Prepare
    uses: Ultimaker/embedded-workflows/.github/workflows/build.yml@main
    with:
      RELEASE_VERSION: ${{ needs.Prepare.outputs.RELEASE_VERSION }}
    secrets: inherit

  Release_Package:
    name: 'Release'
    needs: [Prepare, Shellcheck, Build]
    if: ${{ (success() && needs.Prepare.outputs.RELEASE_REPO != 'none') ||
            (failure() && needs.Build.result == 'success' && needs.Prepare.outputs.RELEASE_REPO == 'packages-dev') }}
    uses: Ultimaker/embedded-workflows/.github/workflows/release_pkg.yml@main
    with:
      RELEASE_REPO: ${{ needs.Prepare.outputs.RELEASE_REPO }}
    secrets: inherit
